# https://play.d2lang.com/?layout=elk

Syntax: {
  basic_types: Basic types
  collections: Collections
  adts: Algebraic Data Types
  records: Records
  tuples: Tuples
  type_aliases: Type Aliases
  pattern_matching: Pattern Matching
  comments: Comments

  basic_types -> collections
  basic_types -> type_aliases
  basic_types -> records

  records -> tuples
  records -> adts

  adts -> pattern_matching
}

Concepts: {
  functional: Functional Programming
  immutability: Immutability
  purity_and_effects: Purity and Effects
  typeclasses: Typeclasses

  functional -> immutability
  functional -> purity_and_effects
}
